# Generated by Django 5.2.6 on 2025-09-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project1Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_id", models.CharField(max_length=50)),
                (
                    "baby1_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Live Born (Well)"),
                            ("2", "Live Born (Sick)"),
                            ("3", "Still Born / IUD"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "baby2_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Live Born (Well)"),
                            ("2", "Live Born (Sick)"),
                            ("3", "Still Born / IUD"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "baby3_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Live Born (Well)"),
                            ("2", "Live Born (Sick)"),
                            ("3", "Still Born / IUD"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "d29_call_status_b1_d14_d7",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Connected"), ("2", "Not Connected")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "d29_call_status_b2_d14_d7",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Connected"), ("2", "Not Connected")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "d29_call_status_b3_d14_d7",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Connected"), ("2", "Not Connected")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "baby1_birthweight",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "baby2_birthweight",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "baby3_birthweight",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "gestationage",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "estimateddateofdelivery",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "q34_estimated_ga_through_ultrasound",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "q35_if_available_estimated_ga_through_ultrasound",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "reg_b1_delivery_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "assistedvaginaldelivery",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reg_b1_total_baby_delivered",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "d29_baby_current_status_b1_d14_d7",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Healthy"), ("2", "Sick"), ("3", "Dead")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "d29_baby_current_status_b2_d14_d7",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Healthy"), ("2", "Sick"), ("3", "Dead")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "d29_baby_current_status_b3_d14_d7",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Healthy"), ("2", "Sick"), ("3", "Dead")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "q17_cause_of_death_d7_if_known",
                    models.JSONField(blank=True, null=True),
                ),
                ("q17a_if_other_specify_d7", models.TextField(blank=True, null=True)),
                ("q17_cause_of_death_d7_b2", models.JSONField(blank=True, null=True)),
                (
                    "q17a_if_other_specify_d7_b2",
                    models.TextField(blank=True, null=True),
                ),
                ("q17_cause_of_death_d7_b3", models.JSONField(blank=True, null=True)),
                ("q17a_if_other_d7_b3", models.TextField(blank=True, null=True)),
                (
                    "baby1_sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Male"),
                            ("2", "Female"),
                            ("3", "Ambiguous"),
                            ("4", "Unknown"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "baby2_sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Male"),
                            ("2", "Female"),
                            ("3", "Ambiguous"),
                            ("4", "Unknown"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "baby3_sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Male"),
                            ("2", "Female"),
                            ("3", "Ambiguous"),
                            ("4", "Unknown"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "reg_b1_delivery_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "delivery_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "delivery_location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Public health facility"),
                            ("2", "Private health facility"),
                            ("3", "Home"),
                            ("4", "On the way"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "d29_baby_death_place_b1_d14_d7",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Public health facility"),
                            ("2", "Private health facility"),
                            ("3", "Home"),
                            ("4", "On the way"),
                            ("5", "Outside District"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "d29_baby_death_place_b2_d14_d7",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Public health facility"),
                            ("2", "Private health facility"),
                            ("3", "Home"),
                            ("4", "On the way"),
                            ("5", "Outside District"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "d29_baby_death_place_b3_d14_d7",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Public health facility"),
                            ("2", "Private health facility"),
                            ("3", "Home"),
                            ("4", "On the way"),
                            ("5", "Outside District"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project_id", models.CharField(default="Project1", max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project2Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_id", models.CharField(max_length=50)),
                (
                    "baby1_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Live Born (Well)"),
                            ("2", "Live Born (Sick)"),
                            ("3", "Still Born / IUD"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "baby2_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Live Born (Well)"),
                            ("2", "Live Born (Sick)"),
                            ("3", "Still Born / IUD"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "baby3_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Live Born (Well)"),
                            ("2", "Live Born (Sick)"),
                            ("3", "Still Born / IUD"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "d29_call_status_b1_d14_d7",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Connected"), ("2", "Not Connected")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "d29_call_status_b2_d14_d7",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Connected"), ("2", "Not Connected")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "d29_call_status_b3_d14_d7",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Connected"), ("2", "Not Connected")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "baby1_birthweight",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "baby2_birthweight",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "baby3_birthweight",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "gestationage",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "estimateddateofdelivery",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "q34_estimated_ga_through_ultrasound",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "q35_if_available_estimated_ga_through_ultrasound",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "reg_b1_delivery_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "assistedvaginaldelivery",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reg_b1_total_baby_delivered",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "d29_baby_current_status_b1_d14_d7",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Healthy"), ("2", "Sick"), ("3", "Dead")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "d29_baby_current_status_b2_d14_d7",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Healthy"), ("2", "Sick"), ("3", "Dead")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "d29_baby_current_status_b3_d14_d7",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Healthy"), ("2", "Sick"), ("3", "Dead")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "q17_cause_of_death_d7_if_known",
                    models.JSONField(blank=True, null=True),
                ),
                ("q17a_if_other_specify_d7", models.TextField(blank=True, null=True)),
                ("q17_cause_of_death_d7_b2", models.JSONField(blank=True, null=True)),
                (
                    "q17a_if_other_specify_d7_b2",
                    models.TextField(blank=True, null=True),
                ),
                ("q17_cause_of_death_d7_b3", models.JSONField(blank=True, null=True)),
                ("q17a_if_other_d7_b3", models.TextField(blank=True, null=True)),
                (
                    "baby1_sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Male"),
                            ("2", "Female"),
                            ("3", "Ambiguous"),
                            ("4", "Unknown"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "baby2_sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Male"),
                            ("2", "Female"),
                            ("3", "Ambiguous"),
                            ("4", "Unknown"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "baby3_sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Male"),
                            ("2", "Female"),
                            ("3", "Ambiguous"),
                            ("4", "Unknown"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "reg_b1_delivery_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "delivery_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "delivery_location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Public health facility"),
                            ("2", "Private health facility"),
                            ("3", "Home"),
                            ("4", "On the way"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "d29_baby_death_place_b1_d14_d7",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Public health facility"),
                            ("2", "Private health facility"),
                            ("3", "Home"),
                            ("4", "On the way"),
                            ("5", "Outside District"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "d29_baby_death_place_b2_d14_d7",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Public health facility"),
                            ("2", "Private health facility"),
                            ("3", "Home"),
                            ("4", "On the way"),
                            ("5", "Outside District"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "d29_baby_death_place_b3_d14_d7",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Public health facility"),
                            ("2", "Private health facility"),
                            ("3", "Home"),
                            ("4", "On the way"),
                            ("5", "Outside District"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project_id", models.CharField(default="Project2", max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
