# Generated by Django 5.2.7 on 2025-10-27 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project1Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_id", models.CharField(max_length=50, unique=True)),
                (
                    "data_access_group",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "baby1_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "baby2_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "baby3_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_current_status_b1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_current_status_b2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_current_status_b3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_call_status_b1_d14_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_call_status_b2_d14_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_call_status_b3_d14_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "baby1_birthweight",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "baby2_birthweight",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "baby3_birthweight",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gestationage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "estimateddateofdelivery",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "q34_estimated_ga_through_ultrasound",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "q35_if_available_estimated_ga_through_ultrasound",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reg_b1_delivery_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "assistedvaginaldelivery",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reg_b1_total_baby_delivered",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_current_status_b1_d14_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_current_status_b2_d14_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_current_status_b3_d14_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_call_status_b1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_call_status_b2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_call_status_b3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "q17_cause_of_death_d7_if_known",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "q17a_if_other_specify_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "q17_cause_of_death_d7_b2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "q17a_if_other_specify_d7_b2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "q17_cause_of_death_d7_b3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "q17a_if_other_d7_b3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("baby1_sex", models.CharField(blank=True, max_length=255, null=True)),
                ("baby2_sex", models.CharField(blank=True, max_length=255, null=True)),
                ("baby3_sex", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "reg_b1_delivery_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "delivery_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "delivery_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_death_place_b1_d14_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_death_place_b2_d14_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_death_place_b3_d14_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_death_date_b1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_death_date_b2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_death_date_b3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_death_place_b1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_death_place_b2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_death_place_b3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_4",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_5",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_6",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_7",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_8",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_9",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_10",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_4",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_5",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_6",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_7",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_8",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_9",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_10",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_4",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_5",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_6",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_7",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_8",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_9",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_10",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estimated_date_of_delivery",
                    models.CharField(
                        blank=True,
                        db_column="estimated_date_of_delivery_p1",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "gestation_age",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ga_edd", models.CharField(blank=True, max_length=100, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project2Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_id", models.CharField(max_length=50, unique=True)),
                (
                    "data_access_group",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "baby1_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "baby2_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "baby3_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_call_status_b1_d14_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_call_status_b2_d14_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_call_status_b3_d14_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_call_status_b1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_call_status_b2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_call_status_b3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "baby1_birthweight",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "baby2_birthweight",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "baby3_birthweight",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gestationage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "estimateddateofdelivery",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "q34_estimated_ga_through_ultrasound",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "q35_if_available_estimated_ga_through_ultrasound",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reg_b1_delivery_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "assistedvaginaldelivery",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reg_b1_total_baby_delivered",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_current_status_b1_d14_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_current_status_b2_d14_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_current_status_b3_d14_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "q17_cause_of_death_d7_if_known",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "q17a_if_other_specify_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "q17_cause_of_death_d7_b2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "q17a_if_other_specify_d7_b2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "q17_cause_of_death_d7_b3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "q17a_if_other_d7_b3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("baby1_sex", models.CharField(blank=True, max_length=255, null=True)),
                ("baby2_sex", models.CharField(blank=True, max_length=255, null=True)),
                ("baby3_sex", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "reg_b1_delivery_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "delivery_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "delivery_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_death_place_b1_d14_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_death_place_b2_d14_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_death_place_b3_d14_d7",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_current_status_b1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_current_status_b2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_current_status_b3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_death_date_b1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_death_date_b2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_death_date_b3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_death_place_b1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_death_place_b2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "d29_baby_death_place_b3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_4",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_5",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_6",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_7",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_8",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_9",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b1_10",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_4",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_5",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_6",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_7",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_8",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_9",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b2_10",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_4",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_5",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_6",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_7",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_8",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_9",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q17_cause_of_death_d29_b3_10",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gestation_age",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estimated_date_of_delivery",
                    models.CharField(
                        blank=True,
                        db_column="estimated_date_of_delivery_p2",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "q40_ga_ultrasound_20wks_weeks",
                    models.CharField(
                        blank=True,
                        db_column="q40_ga_ultrasound_20wks_weeks",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectFetchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255, unique=True)),
                ("last_fetch_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
