# Generated by Django 5.2.6 on 2025-09-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project1record",
            name="data_access_group",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project2record",
            name="data_access_group",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
