# Generated by Django 5.2.6 on 2025-09-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0002_project1record_data_access_group_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project1record",
            old_name="data_access_group",
            new_name="redcap_data_access_group",
        ),
        migrations.RenameField(
            model_name="project2record",
            old_name="data_access_group",
            new_name="redcap_data_access_group",
        ),
        migrations.AlterField(
            model_name="project1record",
            name="baby1_sex",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="baby1_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="baby2_sex",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="baby2_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="baby3_sex",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="baby3_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="d29_baby_current_status_b1_d14_d7",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="d29_baby_current_status_b2_d14_d7",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="d29_baby_current_status_b3_d14_d7",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="d29_baby_death_place_b1_d14_d7",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="d29_baby_death_place_b2_d14_d7",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="d29_baby_death_place_b3_d14_d7",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="d29_call_status_b1_d14_d7",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="d29_call_status_b2_d14_d7",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="d29_call_status_b3_d14_d7",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="delivery_location",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="baby1_sex",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="baby1_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="baby2_sex",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="baby2_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="baby3_sex",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="baby3_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="d29_baby_current_status_b1_d14_d7",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="d29_baby_current_status_b2_d14_d7",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="d29_baby_current_status_b3_d14_d7",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="d29_baby_death_place_b1_d14_d7",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="d29_baby_death_place_b2_d14_d7",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="d29_baby_death_place_b3_d14_d7",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="d29_call_status_b1_d14_d7",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="d29_call_status_b2_d14_d7",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="d29_call_status_b3_d14_d7",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="delivery_location",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
