# Generated by Django 5.2.6 on 2025-10-01 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Dashboard",
            "0003_rename_data_access_group_project1record_redcap_data_access_group_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="project1record",
            old_name="redcap_data_access_group",
            new_name="data_access_group",
        ),
        migrations.RenameField(
            model_name="project2record",
            old_name="redcap_data_access_group",
            new_name="data_access_group",
        ),
    ]
