# Generated by Django 5.2.6 on 2025-10-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Dashboard",
            "0004_rename_redcap_data_access_group_project1record_data_access_group_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project1record",
            name="record_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="record_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
