# Generated by Django 5.2.6 on 2025-10-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0005_alter_project1record_record_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project1record",
            name="last_fetch_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="project2record",
            name="last_fetch_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
