# Generated by Django 5.2.6 on 2025-10-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0006_project1record_last_fetch_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectFetchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100, unique=True)),
                ("last_fetch_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="project1record",
            name="last_fetch_time",
        ),
        migrations.RemoveField(
            model_name="project2record",
            name="last_fetch_time",
        ),
    ]
