# Generated by Django 5.2.6 on 2025-10-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0007_projectfetchlog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project1record",
            name="q17_cause_of_death_d7_b2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="q17_cause_of_death_d7_b3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="q17_cause_of_death_d7_if_known",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="q17a_if_other_d7_b3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="q17a_if_other_specify_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="q17a_if_other_specify_d7_b2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="q17_cause_of_death_d7_b2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="q17_cause_of_death_d7_b3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="q17_cause_of_death_d7_if_known",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="q17a_if_other_d7_b3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="q17a_if_other_specify_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="q17a_if_other_specify_d7_b2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
