# Generated by Django 5.2.6 on 2025-10-06 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0008_alter_project1record_q17_cause_of_death_d7_b2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project1record",
            name="project_id",
        ),
        migrations.RemoveField(
            model_name="project2record",
            name="project_id",
        ),
    ]
