# Generated by Django 5.2.6 on 2025-10-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0009_remove_project1record_project_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project1record",
            name="delivery_location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="delivery_location",
            field=models.TextField(blank=True, null=True),
        ),
    ]
