# Generated by Django 5.2.6 on 2025-10-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0010_alter_project1record_delivery_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project1record",
            name="assistedvaginaldelivery",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="baby1_birthweight",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="baby1_sex",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="baby1_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="baby2_birthweight",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="baby2_sex",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="baby2_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="baby3_birthweight",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="baby3_sex",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="baby3_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="d29_baby_current_status_b1_d14_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="d29_baby_current_status_b2_d14_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="d29_baby_current_status_b3_d14_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="d29_baby_death_place_b1_d14_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="d29_baby_death_place_b2_d14_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="d29_baby_death_place_b3_d14_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="d29_call_status_b1_d14_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="d29_call_status_b2_d14_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="d29_call_status_b3_d14_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="data_access_group",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="delivery_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="delivery_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="estimateddateofdelivery",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="gestationage",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="q34_estimated_ga_through_ultrasound",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="q35_if_available_estimated_ga_through_ultrasound",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="reg_b1_delivery_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="reg_b1_delivery_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project1record",
            name="reg_b1_total_baby_delivered",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="assistedvaginaldelivery",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="baby1_birthweight",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="baby1_sex",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="baby1_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="baby2_birthweight",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="baby2_sex",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="baby2_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="baby3_birthweight",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="baby3_sex",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="baby3_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="d29_baby_current_status_b1_d14_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="d29_baby_current_status_b2_d14_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="d29_baby_current_status_b3_d14_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="d29_baby_death_place_b1_d14_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="d29_baby_death_place_b2_d14_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="d29_baby_death_place_b3_d14_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="d29_call_status_b1_d14_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="d29_call_status_b2_d14_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="d29_call_status_b3_d14_d7",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="data_access_group",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="delivery_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="delivery_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="estimateddateofdelivery",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="gestationage",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="q34_estimated_ga_through_ultrasound",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="q35_if_available_estimated_ga_through_ultrasound",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="reg_b1_delivery_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="reg_b1_delivery_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project2record",
            name="reg_b1_total_baby_delivered",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="projectfetchlog",
            name="project_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
