# Generated by Django 5.2.7 on 2025-10-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0012_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="project1record",
            name="d29_baby_current_status_b1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project1record",
            name="d29_baby_current_status_b2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project1record",
            name="d29_baby_current_status_b3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project1record",
            name="d29_call_status_b1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project1record",
            name="d29_call_status_b2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project1record",
            name="d29_call_status_b3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project2record",
            name="d29_baby_current_status_b1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project2record",
            name="d29_baby_current_status_b2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project2record",
            name="d29_baby_current_status_b3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project2record",
            name="d29_call_status_b1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project2record",
            name="d29_call_status_b2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project2record",
            name="d29_call_status_b3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
